### ISSUE TITLE
Calling /viewer/app without parameters does not show default application but 'Applicatie "null" niet gevonden'

### ISSUE THREAD

**Issue by matthijsln** [B3Partners/tailormap#1090]
When openening the application for the first time index.jsp generates this redirect:

`<meta http-equiv="Refresh" content="0;url=/viewer/app;jsessionid=...?unknown=true"/>`

Internet Explorer splits by all ';' characters so redirects to /viewer/app and drops the unknown=true parameter. Chrome and Firefox keep the full URL including the ';'. In IE this leads to the 'Applicatie "null" niet gevonden' error message.

This can be fixed by adding this to viewer/WEB-INF/web.xml so the ';jsessionid=...' is never added to links:
```
    <session-config>
        <tracking-mode>COOKIE</tracking-mode>
    </session-config>
```
Or we can change the ApplicationActionBean to always redirect to the default application when the name is missing, even without the unknown=true parameter.

Maybe the best solution is to implement both.

**Comment by mprins** [comment]
IE is dead, and we're moving to Spring Boot, so won't be fixed
