### ISSUE TITLE
Impossible to copy application in viewer-admin

### ISSUE THREAD

**Issue by cvanlith** [B3Partners/tailormap#1109]
### Version
Version: | 5.1.5
Build time: | 11.06.2018 @ 09:05:29 CEST
Git branch: | 3a59338fc10907b591d4122317e1fdc73e4b6edb

### Browser info
chrome 67

### URL
https://flamingo4.b3p.nl/viewer-admin

### Where and/or What
make copy of existing application

### What happened
chrome error page:
Er is geen webpagina gevonden voor het webadres: https://flamingo4.b3p.nl/viewer-admin/action/applicationsettings/?copy=t
HTTP ERROR 404

### What did you expect?
new application being a copy of the previous application

### Reproduce
  1.  activate application VGGM
  2.  click on copy button
  3.  fill in new name
  4.  click ok and error message occurs

**Comment by mprins** [comment]
I think this is a deployment issue specific for this server, I have successfully copied Fla apps on other systems with 5.1.5 and 5.3.0-SNAPSHOT

**Comment by mprins** [comment]
Won't fix
