### ISSUE TITLE
Export to csv from attributelist - headers out of sync

### ISSUE THREAD

**Issue by cvanlith** [B3Partners/tailormap#1189]
### Version
Version:	5.3.5
Build time:	24.08.2018 @ 13:58:53 CEST
Build by:	Meine Toonen
Git details
Git branch:	922ab207344b2ef37d9e6143304d80f040138f96
Git remote url	git@github.com:flamingo-mc/flamingo.git
Git commit abbrev id:	922ab20
Git commit full id:	922ab207344b2ef37d9e6143304d80f040138f96
Git commit time:	24.08.2018 @ 13:55:30 CEST

### Browser info
latest chrome

### URL
https://flamingo4.b3p.nl/viewer/app/Solparc-BRK/v1

### Where and/or What
export csv from attributelist

### What happened
the headers are not in sync with the data below

### What did you expect?
same number of headers as number of data items

possibly this is caused bij update of documents feature, underlying json is no longer correct.

**Comment by mprins** [comment]
cannot reproduce
