### ISSUE TITLE
Investigate possibility of setting order of layers separately in ToC and on map

### ISSUE THREAD

**Issue by cvanlith** [B3Partners/tailormap#1303]
It may be usefull to be able to set the order of layers in the ToC independently from the order of the same layers on the map.
It is not clear yet how this may be done without increasing the complexity for the administrator.

**Comment by mprins** [comment]
closing as we are developing the next-gen Tailormap; is required it can be put on tn backlog in https://b3partners.atlassian.net/jira/software/projects/TM/issues/
