### ISSUE TITLE
TMS message: This service can not be updated!

### ISSUE THREAD

**Issue by cvanlith** [B3Partners/tailormap#1411]
### Version
Which version of flamingo do you use: 5.3.11

### Browser info
latest chrome

### URL
https://flamingo5.b3p.nl/viewer-admin/action/geoserviceregistry

### Where and/or What
TMS can not be updated

### What happened
message This service can not be updated! after hitting update button

### What did you expect?
update of service

**Comment by mtoonen** [comment]
Flamingo doesn't parse TMS capabilities, so nothing to update here.

**Comment by cvanlith** [comment]
So this bug must be fixed!

**Comment by cvanlith** [comment]
This form should as a minimum check if the provided url is valid and returns a capabilities document. If possible the document should check the existence of the provided service name. 
Goal is to provide the admin with a means to check if he has filled out the form correctly and a means to check later if the url is still available (if possible including a check on the service name).
