### ISSUE TITLE
Possibility to create a home/reset button in a application

### ISSUE THREAD

**Issue by Frank-van-Rooijen** [B3Partners/tailormap#1669]
### Describe the solution you'd like
A component wich allow you to go to the application's defaulf settings

### Describe alternatives you've considered
Make it possible to do this with a url. This will make it possible to add it as html in the header of a html-component.

### Additional context
Creating a possibility to reset the application's settings will make it easier to start again. This works especially well in large applications with a large amount of layer an in public applications.

**Comment by mtoonen** [comment]
What do you mean exactly: an application as in an application in the viewer? Would an url to that application not suffice? It would reload the application with its "default" settings.

**Comment by mprins** [comment]
closing as we are developing the next-gen Tailormap; is required it can be put on tn backlog in https://b3partners.atlassian.net/jira/software/projects/TM/issues/
