### ISSUE TITLE
WMTS: entering KVP GetCap URL without parameters gives error

### ISSUE THREAD

**Issue by matthijsln** [B3Partners/tailormap#1690]
### Version
5.3.14 

### URL
websg02

### Where and/or What
viewer-admin, geoserviceregistry, add service, Protocol: Tiled, Tiling Protocol: WMTS

### What happened
Enter WMTS KVP URL without parameters: `http://mapproxy.b3p.nl/service`

1. Page shows exception
2. A geoservice without a name is created but can't be edited/deleted

### Server log

<details><summary>relevant section of the server log:</summary>
java.lang.NullPointerException
	nl.b3p.viewer.admin.stripes.GeoServiceActionBean.edit(GeoServiceActionBean.java:446)
	nl.b3p.viewer.admin.stripes.GeoServiceActionBean.add(GeoServiceActionBean.java:802)
</details>

**Comment by mprins** [comment]
docs state you must give a capabilities url: https://github.com/flamingo-geocms/flamingo/wiki/WMTS-support#functional-design

**Comment by matthijsln** [comment]
A KVP URL is a GetCap URL.

**Comment by matthijsln** [comment]
The undeletable empty service is still a bug.

**Comment by mtoonen** [comment]
Undeletable empty service is something different: should be a separate issue
If I remember correctly, retrieving capabilities is not defined in specification so you can't be sure how to handle this

**Comment by matthijsln** [comment]
> **8.1.1 GetCapabilities request HTTP KVP encoding**
> A client performs a GetCapabilities operation using KVP over HTTP by sending a GET
> or POST HTTP message with the 'request' parameter set to 'GetCapabilities'.

**Comment by mtoonen** [comment]
Hmm, then I don't know. Wasn't required when implemented. Services sometimes publish the wmts in just a file (ArcGIS ?), with not requestparams.

**Comment by mprins** [comment]
GetCapabilities is a required function for "procedure oriented architectural style" [dynamic content using messages in KVP, XML, SOAP] but not for "resource oriented architectural style" [static content]  (which requires a "ServiceMetadata" document and tile and optional Featureinfo "documents" aka RESTful)

As documented on page xiii of the "07-057r7_Web_Map_Tile_Service_Standard"

so I'm closing this
