### ISSUE TITLE
Show total Attributelist results in LayerSelector

### ISSUE THREAD

**Issue by geertplaisier** [B3Partners/tailormap#541]
Now you have to switch between layers in the LayerSelector to find out if there are any results for that layer. When we add the totals (for example behind the layer name) it would not be necessary to first select a layer to see if there are any results.

Especially when combined with issue #540 this would give a nice overview of the Attributelist results.

**Comment by geertplaisier** [comment]
See branch [feat/attributelist-totals](https://github.com/flamingo-geocms/flamingo/tree/feat/attributelist-totals)

**Comment by mprins** [comment]
sometimes we don't (at least not exactly) know the number of results 

see also #650

**Comment by mprins** [comment]
won't fix
