### ISSUE TITLE
redlining colors different on screen and print

### ISSUE THREAD

**Issue by cvanlith** [B3Partners/tailormap#932]
### Version
5.0.0-SNAPSHOT-c9dc2ea

### Browser info
Google Chrome is up-to-date
Versie 62.0.3202.62 (Officiële build) (64-bits)

### URL
https://flamingo4.b3p.nl/viewer-admin

### Where and/or What
redlining tool - chosing colors

### What happened
color in print differs from color on the map

### What did you expect?
same color as in color picker

### Reproduce
map green, print blue
sometimes als colors wrong on map
after saving and reloading colors different

**Comment by mprins** [comment]
cannot reproduce
